name: Publish Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download ipregion.sh
        run: |
          echo "📥 Downloading ipregion.sh..."
          curl -fsSL https://raw.githubusercontent.com/vernette/ipregion/refs/heads/master/ipregion.sh -o ipregion.sh
          echo "✅ File downloaded successfully"
          ls -la ipregion.sh

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: '**/package.json'  # Изменяем путь кеша

      - name: Install dependencies
        run: npm install  # Используем install вместо ci

      # --- Публикация в npmjs.org ---
      - name: Setup .npmrc for npmjs.org
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      # Проверяем, что токен существует
      - name: Verify NPM Token
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "❌ NPM_TOKEN secret is not set"
            exit 1
          fi
          echo "✅ NPM_TOKEN is configured"

      - name: Publish to npmjs.org
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
